In [1]:
import numpy as np

In [2]:
x = np.arange(12)

In [3]:
y = x

In [4]:
y = y.reshape(3, 4)

In [5]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
x += 1

In [8]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
x = x + 1

In [11]:
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])